---
- name: Install node and npm 
  hosts: node
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install nodejs and npm
      apt: 
        pkg: 
          - nodejs
          - npm
        
- name: Deploy nodejs app
  hosts: node
  tasks:
    - name: unarchive nodejs folder to a server
      unarchive:
        src: /home/monire/bootcamp/ansible/node/nodejs-app
        dest: /root/
    - name: Install dependencies
      npm:
        path: /root/package
    - name: start the application
      command:
        chdir: /root/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Insure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}  
  

    